# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nightmare/Documents/GitHub/CPU-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nightmare/Documents/GitHub/CPU-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nightmare/Documents/GitHub/CPU-project/CMakeFiles /home/nightmare/Documents/GitHub/CPU-project//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nightmare/Documents/GitHub/CPU-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Assembler

# Build rule for target.
Assembler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Assembler
.PHONY : Assembler

# fast build rule for target.
Assembler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/build
.PHONY : Assembler/fast

#=============================================================================
# Target rules for targets named Interpreter

# Build rule for target.
Interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Interpreter
.PHONY : Interpreter

# fast build rule for target.
Interpreter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/build
.PHONY : Interpreter/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

src/assembler/addr_translation.o: src/assembler/addr_translation.c.o
.PHONY : src/assembler/addr_translation.o

# target to build an object file
src/assembler/addr_translation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/addr_translation.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/addr_translation.c.o
.PHONY : src/assembler/addr_translation.c.o

src/assembler/addr_translation.i: src/assembler/addr_translation.c.i
.PHONY : src/assembler/addr_translation.i

# target to preprocess a source file
src/assembler/addr_translation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/addr_translation.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/addr_translation.c.i
.PHONY : src/assembler/addr_translation.c.i

src/assembler/addr_translation.s: src/assembler/addr_translation.c.s
.PHONY : src/assembler/addr_translation.s

# target to generate assembly for a file
src/assembler/addr_translation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/addr_translation.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/addr_translation.c.s
.PHONY : src/assembler/addr_translation.c.s

src/assembler/checks.o: src/assembler/checks.c.o
.PHONY : src/assembler/checks.o

# target to build an object file
src/assembler/checks.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/checks.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/checks.c.o
.PHONY : src/assembler/checks.c.o

src/assembler/checks.i: src/assembler/checks.c.i
.PHONY : src/assembler/checks.i

# target to preprocess a source file
src/assembler/checks.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/checks.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/checks.c.i
.PHONY : src/assembler/checks.c.i

src/assembler/checks.s: src/assembler/checks.c.s
.PHONY : src/assembler/checks.s

# target to generate assembly for a file
src/assembler/checks.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/checks.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/checks.c.s
.PHONY : src/assembler/checks.c.s

src/assembler/main.o: src/assembler/main.c.o
.PHONY : src/assembler/main.o

# target to build an object file
src/assembler/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/main.c.o
.PHONY : src/assembler/main.c.o

src/assembler/main.i: src/assembler/main.c.i
.PHONY : src/assembler/main.i

# target to preprocess a source file
src/assembler/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/main.c.i
.PHONY : src/assembler/main.c.i

src/assembler/main.s: src/assembler/main.c.s
.PHONY : src/assembler/main.s

# target to generate assembly for a file
src/assembler/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/main.c.s
.PHONY : src/assembler/main.c.s

src/assembler/parsing.o: src/assembler/parsing.c.o
.PHONY : src/assembler/parsing.o

# target to build an object file
src/assembler/parsing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/parsing.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/parsing.c.o
.PHONY : src/assembler/parsing.c.o

src/assembler/parsing.i: src/assembler/parsing.c.i
.PHONY : src/assembler/parsing.i

# target to preprocess a source file
src/assembler/parsing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/parsing.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/parsing.c.i
.PHONY : src/assembler/parsing.c.i

src/assembler/parsing.s: src/assembler/parsing.c.s
.PHONY : src/assembler/parsing.s

# target to generate assembly for a file
src/assembler/parsing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/parsing.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/parsing.c.s
.PHONY : src/assembler/parsing.c.s

src/assembler/translator.o: src/assembler/translator.c.o
.PHONY : src/assembler/translator.o

# target to build an object file
src/assembler/translator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/translator.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/translator.c.o
.PHONY : src/assembler/translator.c.o

src/assembler/translator.i: src/assembler/translator.c.i
.PHONY : src/assembler/translator.i

# target to preprocess a source file
src/assembler/translator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/translator.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/translator.c.i
.PHONY : src/assembler/translator.c.i

src/assembler/translator.s: src/assembler/translator.c.s
.PHONY : src/assembler/translator.s

# target to generate assembly for a file
src/assembler/translator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/assembler/translator.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/assembler/translator.c.s
.PHONY : src/assembler/translator.c.s

src/const.o: src/const.c.o
.PHONY : src/const.o

# target to build an object file
src/const.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/const.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/const.c.o
.PHONY : src/const.c.o

src/const.i: src/const.c.i
.PHONY : src/const.i

# target to preprocess a source file
src/const.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/const.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/const.c.i
.PHONY : src/const.c.i

src/const.s: src/const.c.s
.PHONY : src/const.s

# target to generate assembly for a file
src/const.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/const.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/const.c.s
.PHONY : src/const.c.s

src/file_processer.o: src/file_processer.c.o
.PHONY : src/file_processer.o

# target to build an object file
src/file_processer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/file_processer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/file_processer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/file_processer.c.o
.PHONY : src/file_processer.c.o

src/file_processer.i: src/file_processer.c.i
.PHONY : src/file_processer.i

# target to preprocess a source file
src/file_processer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/file_processer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/file_processer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/file_processer.c.i
.PHONY : src/file_processer.c.i

src/file_processer.s: src/file_processer.c.s
.PHONY : src/file_processer.s

# target to generate assembly for a file
src/file_processer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/file_processer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/file_processer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/file_processer.c.s
.PHONY : src/file_processer.c.s

src/interpreter/instruction_set.o: src/interpreter/instruction_set.c.o
.PHONY : src/interpreter/instruction_set.o

# target to build an object file
src/interpreter/instruction_set.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/instruction_set.c.o
.PHONY : src/interpreter/instruction_set.c.o

src/interpreter/instruction_set.i: src/interpreter/instruction_set.c.i
.PHONY : src/interpreter/instruction_set.i

# target to preprocess a source file
src/interpreter/instruction_set.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/instruction_set.c.i
.PHONY : src/interpreter/instruction_set.c.i

src/interpreter/instruction_set.s: src/interpreter/instruction_set.c.s
.PHONY : src/interpreter/instruction_set.s

# target to generate assembly for a file
src/interpreter/instruction_set.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/instruction_set.c.s
.PHONY : src/interpreter/instruction_set.c.s

src/interpreter/main.o: src/interpreter/main.c.o
.PHONY : src/interpreter/main.o

# target to build an object file
src/interpreter/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/main.c.o
.PHONY : src/interpreter/main.c.o

src/interpreter/main.i: src/interpreter/main.c.i
.PHONY : src/interpreter/main.i

# target to preprocess a source file
src/interpreter/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/main.c.i
.PHONY : src/interpreter/main.c.i

src/interpreter/main.s: src/interpreter/main.c.s
.PHONY : src/interpreter/main.s

# target to generate assembly for a file
src/interpreter/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/main.c.s
.PHONY : src/interpreter/main.c.s

src/interpreter/parsing.o: src/interpreter/parsing.c.o
.PHONY : src/interpreter/parsing.o

# target to build an object file
src/interpreter/parsing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/parsing.c.o
.PHONY : src/interpreter/parsing.c.o

src/interpreter/parsing.i: src/interpreter/parsing.c.i
.PHONY : src/interpreter/parsing.i

# target to preprocess a source file
src/interpreter/parsing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/parsing.c.i
.PHONY : src/interpreter/parsing.c.i

src/interpreter/parsing.s: src/interpreter/parsing.c.s
.PHONY : src/interpreter/parsing.s

# target to generate assembly for a file
src/interpreter/parsing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/parsing.c.s
.PHONY : src/interpreter/parsing.c.s

src/interpreter/runtime.o: src/interpreter/runtime.c.o
.PHONY : src/interpreter/runtime.o

# target to build an object file
src/interpreter/runtime.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/runtime.c.o
.PHONY : src/interpreter/runtime.c.o

src/interpreter/runtime.i: src/interpreter/runtime.c.i
.PHONY : src/interpreter/runtime.i

# target to preprocess a source file
src/interpreter/runtime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/runtime.c.i
.PHONY : src/interpreter/runtime.c.i

src/interpreter/runtime.s: src/interpreter/runtime.c.s
.PHONY : src/interpreter/runtime.s

# target to generate assembly for a file
src/interpreter/runtime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/interpreter/runtime.c.s
.PHONY : src/interpreter/runtime.c.s

src/parsing.o: src/parsing.c.o
.PHONY : src/parsing.o

# target to build an object file
src/parsing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/parsing.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/parsing.c.o
.PHONY : src/parsing.c.o

src/parsing.i: src/parsing.c.i
.PHONY : src/parsing.i

# target to preprocess a source file
src/parsing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/parsing.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/parsing.c.i
.PHONY : src/parsing.c.i

src/parsing.s: src/parsing.c.s
.PHONY : src/parsing.s

# target to generate assembly for a file
src/parsing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/parsing.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/parsing.c.s
.PHONY : src/parsing.c.s

src/print.o: src/print.c.o
.PHONY : src/print.o

# target to build an object file
src/print.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/print.c.o
.PHONY : src/print.c.o

src/print.i: src/print.c.i
.PHONY : src/print.i

# target to preprocess a source file
src/print.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/print.c.i
.PHONY : src/print.c.i

src/print.s: src/print.c.s
.PHONY : src/print.s

# target to generate assembly for a file
src/print.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/print.c.s
.PHONY : src/print.c.s

src/words.o: src/words.c.o
.PHONY : src/words.o

# target to build an object file
src/words.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/words.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/words.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/words.c.o
.PHONY : src/words.c.o

src/words.i: src/words.c.i
.PHONY : src/words.i

# target to preprocess a source file
src/words.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/words.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/words.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/words.c.i
.PHONY : src/words.c.i

src/words.s: src/words.c.s
.PHONY : src/words.s

# target to generate assembly for a file
src/words.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assembler.dir/build.make CMakeFiles/Assembler.dir/src/words.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Interpreter.dir/build.make CMakeFiles/Interpreter.dir/src/words.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/words.c.s
.PHONY : src/words.c.s

tests/tests/test_assembler_compiles.o: tests/tests/test_assembler_compiles.c.o
.PHONY : tests/tests/test_assembler_compiles.o

# target to build an object file
tests/tests/test_assembler_compiles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/tests/test_assembler_compiles.c.o
.PHONY : tests/tests/test_assembler_compiles.c.o

tests/tests/test_assembler_compiles.i: tests/tests/test_assembler_compiles.c.i
.PHONY : tests/tests/test_assembler_compiles.i

# target to preprocess a source file
tests/tests/test_assembler_compiles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/tests/test_assembler_compiles.c.i
.PHONY : tests/tests/test_assembler_compiles.c.i

tests/tests/test_assembler_compiles.s: tests/tests/test_assembler_compiles.c.s
.PHONY : tests/tests/test_assembler_compiles.s

# target to generate assembly for a file
tests/tests/test_assembler_compiles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/tests/test_assembler_compiles.c.s
.PHONY : tests/tests/test_assembler_compiles.c.s

thirdparty/Unity/src/unity.o: thirdparty/Unity/src/unity.c.o
.PHONY : thirdparty/Unity/src/unity.o

# target to build an object file
thirdparty/Unity/src/unity.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/thirdparty/Unity/src/unity.c.o
.PHONY : thirdparty/Unity/src/unity.c.o

thirdparty/Unity/src/unity.i: thirdparty/Unity/src/unity.c.i
.PHONY : thirdparty/Unity/src/unity.i

# target to preprocess a source file
thirdparty/Unity/src/unity.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/thirdparty/Unity/src/unity.c.i
.PHONY : thirdparty/Unity/src/unity.c.i

thirdparty/Unity/src/unity.s: thirdparty/Unity/src/unity.c.s
.PHONY : thirdparty/Unity/src/unity.s

# target to generate assembly for a file
thirdparty/Unity/src/unity.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/thirdparty/Unity/src/unity.c.s
.PHONY : thirdparty/Unity/src/unity.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Assembler"
	@echo "... Interpreter"
	@echo "... run_tests"
	@echo "... src/assembler/addr_translation.o"
	@echo "... src/assembler/addr_translation.i"
	@echo "... src/assembler/addr_translation.s"
	@echo "... src/assembler/checks.o"
	@echo "... src/assembler/checks.i"
	@echo "... src/assembler/checks.s"
	@echo "... src/assembler/main.o"
	@echo "... src/assembler/main.i"
	@echo "... src/assembler/main.s"
	@echo "... src/assembler/parsing.o"
	@echo "... src/assembler/parsing.i"
	@echo "... src/assembler/parsing.s"
	@echo "... src/assembler/translator.o"
	@echo "... src/assembler/translator.i"
	@echo "... src/assembler/translator.s"
	@echo "... src/const.o"
	@echo "... src/const.i"
	@echo "... src/const.s"
	@echo "... src/file_processer.o"
	@echo "... src/file_processer.i"
	@echo "... src/file_processer.s"
	@echo "... src/interpreter/instruction_set.o"
	@echo "... src/interpreter/instruction_set.i"
	@echo "... src/interpreter/instruction_set.s"
	@echo "... src/interpreter/main.o"
	@echo "... src/interpreter/main.i"
	@echo "... src/interpreter/main.s"
	@echo "... src/interpreter/parsing.o"
	@echo "... src/interpreter/parsing.i"
	@echo "... src/interpreter/parsing.s"
	@echo "... src/interpreter/runtime.o"
	@echo "... src/interpreter/runtime.i"
	@echo "... src/interpreter/runtime.s"
	@echo "... src/parsing.o"
	@echo "... src/parsing.i"
	@echo "... src/parsing.s"
	@echo "... src/print.o"
	@echo "... src/print.i"
	@echo "... src/print.s"
	@echo "... src/words.o"
	@echo "... src/words.i"
	@echo "... src/words.s"
	@echo "... tests/tests/test_assembler_compiles.o"
	@echo "... tests/tests/test_assembler_compiles.i"
	@echo "... tests/tests/test_assembler_compiles.s"
	@echo "... thirdparty/Unity/src/unity.o"
	@echo "... thirdparty/Unity/src/unity.i"
	@echo "... thirdparty/Unity/src/unity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

