name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests if available
      working-directory: ${{github.workspace}}/build
      run: |
        if [ -f run_tests ]; then
          ./run_tests
        else
          echo "No tests to run"
        fi

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: ${{github.workspace}}/build/*
